#!/usr/bin/env python3
from pathlib import Path
import sys
if len(sys.argv)!=2: raise SystemExit('usage: patch_performance_v1.py <scripts-root>')
root=Path(sys.argv[1])

def patch(rel, reps):
    p=root/rel
    t=p.read_text(encoding='utf-8-sig')
    for old,new,label in reps:
        n=t.count(old)
        if n!=1: raise SystemExit(f'{rel} {label}: expected 1 match, got {n}')
        t=t.replace(old,new,1)
    p.write_text(t,encoding='utf-8',newline='\n')
    print('patched',rel)

patch('com/brockw/stickwar/engine/HealthBar.as',[
('''            this.redBar.graphics.lineTo(-BAR_WIDTH / 2 + BAR_WIDTH * this._health / this._totalHealth,-BAR_HEIGHT / 2);\n         }\n''','''            this.redBar.graphics.lineTo(-BAR_WIDTH / 2 + BAR_WIDTH * this._health / this._totalHealth,-BAR_HEIGHT / 2);\n            this.isFirst = false;\n         }\n''','clear first-draw flag'),
])

patch('com/brockw/stickwar/engine/SpatialHash.as',[
('''      internal var visited:Dictionary;\n      \n      internal var game:StickWar;\n''','''      internal var visited:Dictionary;\n      \n      private var visitMarks:Vector.<int>;\n      \n      private var visitStamp:int;\n      \n      private var emptyPartition:Vector.<Entity>;\n      \n      internal var game:StickWar;\n''','visit fields'),
('''         this.visited = new Dictionary();\n         this.width = width;\n''','''         this.visited = new Dictionary();\n         this.visitMarks = new Vector.<int>(1024,false);\n         this.visitStamp = 0;\n         this.emptyPartition = new Vector.<Entity>();\n         this.width = width;\n''','visit init'),
('''      public function add(entity:Entity) : void\n      {\n         var x:int = entity.px / this.boxWidth;\n         var y:int = entity.py / this.boxHeight;\n         if(x < 0 || x >= this.cols || y < 0 || y >= this.rows)\n         {\n            return;\n         }\n         Vector.<Entity>(this.partitions[this.cols * y + x])[this.partitionSizes[this.cols * y + x]] = entity;\n         ++this.partitionSizes[this.cols * y + x];\n         if(x > 0)\n         {\n            Vector.<Entity>(this.partitions[this.cols * y + x - 1])[this.partitionSizes[this.cols * y + x - 1]] = entity;\n            ++this.partitionSizes[this.cols * y + x - 1];\n         }\n         if(y > 0)\n         {\n            Vector.<Entity>(this.partitions[this.cols * (y - 1) + x])[this.partitionSizes[this.cols * (y - 1) + x]] = entity;\n            ++this.partitionSizes[this.cols * (y - 1) + x];\n         }\n         if(y < this.rows - 1)\n         {\n            Vector.<Entity>(this.partitions[this.cols * (y + 1) + x])[this.partitionSizes[this.cols * (y + 1) + x]] = entity;\n            ++this.partitionSizes[this.cols * (y + 1) + x];\n         }\n         if(x < this.cols - 1)\n         {\n            Vector.<Entity>(this.partitions[this.cols * y + x + 1])[this.partitionSizes[this.cols * y + x + 1]] = entity;\n            ++this.partitionSizes[this.cols * y + x + 1];\n         }\n      }\n''','''      private function addToPartition(index:int, entity:Entity) : void\n      {\n         var size:int = this.partitionSizes[index];\n         if(size >= this.partitions[index].length)\n         {\n            this.partitions[index].length = size + 64;\n         }\n         this.partitions[index][size] = entity;\n         this.partitionSizes[index] = size + 1;\n      }\n      \n      public function add(entity:Entity) : void\n      {\n         var x:int = entity.px / this.boxWidth;\n         var y:int = entity.py / this.boxHeight;\n         if(x < 0 || x >= this.cols || y < 0 || y >= this.rows)\n         {\n            return;\n         }\n         var index:int = this.cols * y + x;\n         this.addToPartition(index,entity);\n         if(x > 0)\n         {\n            this.addToPartition(index - 1,entity);\n         }\n         if(y > 0)\n         {\n            this.addToPartition(index - this.cols,entity);\n         }\n         if(y < this.rows - 1)\n         {\n            this.addToPartition(index + this.cols,entity);\n         }\n         if(x < this.cols - 1)\n         {\n            this.addToPartition(index + 1,entity);\n         }\n      }\n''','dynamic partition add'),
('''      public function mapInArea(xs:Number, ys:Number, xe:Number, ye:Number, f:Function, includeWalls:Boolean = true) : void\n      {\n         var id:String = null;\n         var wall:Wall = null;\n         var y:int = 0;\n         var i:int = 0;\n''','''      public function mapInArea(xs:Number, ys:Number, xe:Number, ye:Number, f:Function, includeWalls:Boolean = true) : void\n      {\n         var wall:Wall = null;\n         var entity:Entity = null;\n         var entityId:int = 0;\n         var y:int = 0;\n         var i:int = 0;\n         ++this.visitStamp;\n''','map vars'),
('''                  for(i = 0; i < this.partitionSizes[this.cols * y + x]; i++)\n                  {\n                     if(!(this.partitions[this.cols * y + x][i].id in this.visited))\n                     {\n                        f(this.partitions[this.cols * y + x][i]);\n                        this.visited[this.partitions[this.cols * y + x][i].id] = 0;\n                     }\n                  }\n''','''                  for(i = 0; i < this.partitionSizes[this.cols * y + x]; i++)\n                  {\n                     entity = this.partitions[this.cols * y + x][i];\n                     entityId = entity.id;\n                     if(entityId >= this.visitMarks.length)\n                     {\n                        this.visitMarks.length = entityId + 256;\n                     }\n                     if(this.visitMarks[entityId] != this.visitStamp)\n                     {\n                        this.visitMarks[entityId] = this.visitStamp;\n                        f(entity);\n                     }\n                  }\n''','stamp dedupe'),
('''         for(id in this.visited)\n         {\n            delete this.visited[id];\n         }\n''','''         // visitMarks uses an incrementing stamp, avoiding Dictionary insert/delete churn per query.\n''','remove dictionary cleanup'),
('''            return new Vector.<Entity>();\n         }\n         return this.partitions[this.cols * y + x];\n      }\n      \n      public function getNearbyEntitysXY''','''            return this.emptyPartition;\n         }\n         return this.partitions[this.cols * y + x];\n      }\n      \n      public function getNearbyEntitysXY''','empty nearby entity'),
('''            return new Vector.<Entity>();\n         }\n         return this.partitions[this.cols * y + x];\n      }\n      \n      public function getNumberOfNearbyEntitysXY''','''            return this.emptyPartition;\n         }\n         return this.partitions[this.cols * y + x];\n      }\n      \n      public function getNumberOfNearbyEntitysXY''','empty nearby xy'),
('''      public function clear() : void\n      {\n         var x:int = 0;\n         for(var y:int = 0; y < this.rows; y++)\n         {\n            for(x = 0; x < this.cols; x++)\n            {\n               this.partitionSizes[this.cols * y + x] = 0;\n            }\n         }\n      }\n''','''      public function clear() : void\n      {\n         for(var i:int = 0; i < this.partitionSizes.length; i++)\n         {\n            this.partitionSizes[i] = 0;\n         }\n      }\n''','flat clear'),
])

patch('com/brockw/stickwar/engine/StickWar.as',[
('''         this._spatialHash = new SpatialHash(this,this.map.width,this.map.height,50,this.map.height / 7,100);\n''','''         // Expansion battles can pack far more actors into one spatial bucket than vanilla.\n         this._spatialHash = new SpatialHash(this,this.map.width,this.map.height,50,this.map.height / 7,512);\n''','larger spatial buckets'),
('''         this.projectileManager.airEffects.splice(0,this.projectileManager.airEffects.length);\n''','''         this.projectileManager.airEffects.length = 0;\n''','clear air effects'),
('''      private function sortZ(dParent:DisplayObjectContainer, skip:int = 20) : void\n      {\n         var bFlipped:Boolean = false;\n         var o:int = 0;\n         skip = 1;\n         if(dParent.numChildren > 60)\n         {\n            skip = 10 + (dParent.numChildren - 60);\n         }\n         var isOdd:int = this.random.nextInt() % skip;\n         for(var i:int = dParent.numChildren - 1 - isOdd; i > 0; )\n         {\n            bFlipped = false;\n            for(o = 0; o < i; o++)\n            {\n               if(dParent.getChildAt(o) is Entity && dParent.getChildAt(o + 1) is Entity)\n               {\n                  if(Entity(dParent.getChildAt(o)).py > Entity(dParent.getChildAt(o + 1)).py)\n                  {\n                     dParent.swapChildrenAt(o,o + 1);\n                     bFlipped = true;\n                  }\n               }\n            }\n            if(!bFlipped)\n            {\n               return;\n            }\n            i -= skip;\n         }\n      }\n''','''      private function sortZ(dParent:DisplayObjectContainer, skip:int = 20) : void\n      {\n         // Two linear cocktail passes keep depth order converging without the old repeated bubble-sort scans.\n         var o:int = 0;\n         var left:Entity = null;\n         var right:Entity = null;\n         for(o = 0; o < dParent.numChildren - 1; o++)\n         {\n            if(dParent.getChildAt(o) is Entity && dParent.getChildAt(o + 1) is Entity)\n            {\n               left = Entity(dParent.getChildAt(o));\n               right = Entity(dParent.getChildAt(o + 1));\n               if(left.py > right.py)\n               {\n                  dParent.swapChildrenAt(o,o + 1);\n               }\n            }\n         }\n         for(o = dParent.numChildren - 1; o > 0; o--)\n         {\n            if(dParent.getChildAt(o - 1) is Entity && dParent.getChildAt(o) is Entity)\n            {\n               left = Entity(dParent.getChildAt(o - 1));\n               right = Entity(dParent.getChildAt(o));\n               if(left.py > right.py)\n               {\n                  dParent.swapChildrenAt(o - 1,o);\n               }\n            }\n         }\n      }\n''','linear depth sort'),
])

patch('com/brockw/stickwar/engine/projectile/ProjectileManager.as',[
('''      public function update(game:StickWar) : void\n      {\n         var i:int = 0;\n         var p:Projectile = null;\n         for(i = 0; i < this.projectiles.length; i++)\n         {\n            if(!Projectile(this.projectiles[i]).isInFlight())\n            {\n               p = this.projectiles.splice(i,1)[0];\n               p.framesDead = 0;\n               this._waitingToBeCleaned.push(p);\n            }\n            else\n            {\n               this.projectiles[i].update(game);\n            }\n         }\n         for(i = 0; i < this._waitingToBeCleaned.length; i++)\n         {\n            ++this._waitingToBeCleaned[i].framesDead;\n         }\n         while(this._waitingToBeCleaned.length != 0 && Boolean(this._waitingToBeCleaned[0].isReadyForCleanup()))\n         {\n            p = this._waitingToBeCleaned.shift();\n            if(game.battlefield.contains(p))\n            {\n               game.battlefield.removeChild(p);\n            }\n            this._projectileMap[p.type].returnItem(p);\n         }\n      }\n''','''      public function update(game:StickWar) : void\n      {\n         var i:int = 0;\n         var last:int = 0;\n         var p:Projectile = null;\n         // Swap-remove finished projectiles: no Array.splice compaction and no skipped successor.\n         i = 0;\n         while(i < this.projectiles.length)\n         {\n            p = Projectile(this.projectiles[i]);\n            if(!p.isInFlight())\n            {\n               last = this.projectiles.length - 1;\n               this.projectiles[i] = this.projectiles[last];\n               this.projectiles.pop();\n               p.framesDead = 0;\n               this._waitingToBeCleaned.push(p);\n            }\n            else\n            {\n               p.update(game);\n               ++i;\n            }\n         }\n         // Dead effects are independent; reclaim ready entries in-place instead of shifting the whole queue.\n         i = this._waitingToBeCleaned.length - 1;\n         while(i >= 0)\n         {\n            p = Projectile(this._waitingToBeCleaned[i]);\n            ++p.framesDead;\n            if(p.isReadyForCleanup())\n            {\n               last = this._waitingToBeCleaned.length - 1;\n               this._waitingToBeCleaned[i] = this._waitingToBeCleaned[last];\n               this._waitingToBeCleaned.pop();\n               if(game.battlefield.contains(p))\n               {\n                  game.battlefield.removeChild(p);\n               }\n               this._projectileMap[p.type].returnItem(p);\n            }\n            --i;\n         }\n      }\n''','swap-remove projectiles'),
])

patch('com/brockw/stickwar/engine/Team/Team.as',[
('''      private var _deadUnits:Array;\n      \n      private var _enemyTeam:Team;\n''','''      private var _deadUnits:Array;\n      \n      private var _lastStatueType:String;\n      \n      private var _enemyTeam:Team;\n''','statue cache field'),
('''         this._deadUnits = new Array();\n         this.game = game;\n''','''         this._deadUnits = new Array();\n         this._lastStatueType = null;\n         this.game = game;\n''','statue cache init'),
('''      public function updateStatue() : void\n      {\n         if(this._statueType != "default")\n         {\n            this.statue.mc.statue.gotoAndStop(this._statueType);\n         }\n         else\n         {\n            this.statue.mc.statue.gotoAndStop("default");\n         }\n      }\n''','''      public function updateStatue() : void\n      {\n         var nextType:String = this._statueType != "default" ? this._statueType : "default";\n         if(this._lastStatueType != nextType)\n         {\n            this.statue.mc.statue.gotoAndStop(nextType);\n            this._lastStatueType = nextType;\n         }\n      }\n''','statue dirty update'),
('''         if(this._deadUnits.length > 0 && Unit(this._deadUnits[0]).timeOfDeath > 30 * 20)\n         {\n            this.removeUnitCompletely(this._deadUnits.shift(),game);\n         }\n         var u:UnitMove = new UnitMove();\n         u.moveType = UnitCommand.MOVE;\n         for(unit in this.garrisonedUnits)\n         {\n            u.units.push(this.garrisonedUnits[unit].id);\n         }\n         u.owner = this.id;\n         u.arg0 = this.homeX - this.direction * game.map.screenWidth / 3;\n         u.arg1 = game.map.height / 2;\n         u.execute(game);\n''','''         var cleanupBudget:int = 8;\n         while(this._deadUnits.length > 0 && Unit(this._deadUnits[0]).timeOfDeath > 30 * 20 && cleanupBudget > 0)\n         {\n            this.removeUnitCompletely(this._deadUnits.shift(),game);\n            --cleanupBudget;\n         }\n         // Vanilla allocated/executed an empty UnitMove every frame even with nothing garrisoned.\n         var u:UnitMove = null;\n         for(unit in this.garrisonedUnits)\n         {\n            if(u == null)\n            {\n               u = new UnitMove();\n               u.moveType = UnitCommand.MOVE;\n            }\n            u.units.push(this.garrisonedUnits[unit].id);\n         }\n         if(u != null)\n         {\n            u.owner = this.id;\n            u.arg0 = this.homeX - this.direction * game.map.screenWidth / 3;\n            u.arg1 = game.map.height / 2;\n            u.execute(game);\n         }\n''','dead cleanup and empty garrison allocation'),
])

patch('com/brockw/stickwar/engine/units/Unit.as',[
('''      private var _healthBar:HealthBar;\n      \n      private var _damageToDeal:Number;\n''','''      private var _healthBar:HealthBar;\n      \n      private var _selectionVisualState:int = -99;\n      \n      private var _damageToDeal:Number;\n''','selection cache field'),
('''         if(this.shadowSprite == null)\n         {\n            this.shadowSprite = new MovieClip();\n            this.addChild(this.shadowSprite);\n''','''         if(this.shadowSprite == null)\n         {\n            this.shadowSprite = new MovieClip();\n            this._selectionVisualState = -99;\n            this.addChild(this.shadowSprite);\n''','selection cache reset'),
('''      public function sqrDistanceToTarget(target:Unit) : Number\n      {\n         if(target == null)\n         {\n            return Number.MAX_VALUE;\n         }\n         return Math.pow(target.px - px,2) + Math.pow(target.py - py,2) * 10;\n      }\n      \n      public function sqrDistanceTo(target:Unit) : Number\n      {\n         if(target == null)\n         {\n            return Number.MAX_VALUE;\n         }\n         return Math.pow(target.px - px,2) + Math.pow(target.py - py,2);\n      }\n''','''      public function sqrDistanceToTarget(target:Unit) : Number\n      {\n         if(target == null)\n         {\n            return Number.MAX_VALUE;\n         }\n         var xDiff:Number = target.px - px;\n         var yDiff:Number = target.py - py;\n         return xDiff * xDiff + yDiff * yDiff * 10;\n      }\n      \n      public function sqrDistanceTo(target:Unit) : Number\n      {\n         if(target == null)\n         {\n            return Number.MAX_VALUE;\n         }\n         var xDiff:Number = target.px - px;\n         var yDiff:Number = target.py - py;\n         return xDiff * xDiff + yDiff * yDiff;\n      }\n''','distance multiply'),
('''      private function removedSelected() : void\n      {\n         if(this.shadowSprite == null)\n         {\n            return;\n         }\n         this.shadowSprite.graphics.clear();\n''','''      private function removedSelected() : void\n      {\n         if(this.shadowSprite == null)\n         {\n            return;\n         }\n         var nextState:int = this.isAlive() ? 0 : 3;\n         if(this._selectionVisualState == nextState)\n         {\n            return;\n         }\n         this._selectionVisualState = nextState;\n         this.shadowSprite.graphics.clear();\n''','unselected graphics cache'),
('''      private function drawSelected(color:int, thickness:Number) : void\n      {\n         if(this.shadowSprite == null)\n         {\n            return;\n         }\n         this.shadowSprite.graphics.clear();\n''','''      private function drawSelected(color:int, thickness:Number) : void\n      {\n         if(this.shadowSprite == null)\n         {\n            return;\n         }\n         var nextState:int = color == 65280 ? 1 : 2;\n         if(this._selectionVisualState == nextState)\n         {\n            return;\n         }\n         this._selectionVisualState = nextState;\n         this.shadowSprite.graphics.clear();\n''','selected graphics cache'),
('''      protected function fractionOfCollision(unit:Unit, dx:int, dy:int) : Number\n      {\n         return (Math.pow(unit.px + unit.dx - dx - px,2) + Math.pow(unit.py + unit.dy - dy - py,2)) / Math.pow(unit.hitBoxWidth * (this.perspectiveScale + unit.perspectiveScale) / 2,2);\n      }\n      \n      protected function isCollision(unit:Unit, dx:int, dy:int) : Boolean\n      {\n         if(Math.pow(unit.px + unit.dx - dx - px,2) + Math.pow(unit.py + unit.dy - dy - py,2) < Math.pow(unit.hitBoxWidth * (this.perspectiveScale + unit.perspectiveScale) / 2,2))\n         {\n            return true;\n         }\n         return false;\n      }\n''','''      protected function fractionOfCollision(unit:Unit, dx:int, dy:int) : Number\n      {\n         var xDiff:Number = unit.px + unit.dx - dx - px;\n         var yDiff:Number = unit.py + unit.dy - dy - py;\n         var radius:Number = unit.hitBoxWidth * (this.perspectiveScale + unit.perspectiveScale) / 2;\n         return (xDiff * xDiff + yDiff * yDiff) / (radius * radius);\n      }\n      \n      protected function isCollision(unit:Unit, dx:int, dy:int) : Boolean\n      {\n         var xDiff:Number = unit.px + unit.dx - dx - px;\n         var yDiff:Number = unit.py + unit.dy - dy - py;\n         var radius:Number = unit.hitBoxWidth * (this.perspectiveScale + unit.perspectiveScale) / 2;\n         return xDiff * xDiff + yDiff * yDiff < radius * radius;\n      }\n''','collision multiply'),
])

patch('com/brockw/stickwar/engine/BloodManager.as',[
('''      private var ashs:Array;\n      \n      public function BloodManager()\n''','''      private var ashs:Array;\n      \n      private var bloodCursor:int = 0;\n      \n      private var ashCursor:int = 0;\n      \n      public function BloodManager()\n''','ring fields'),
('''         else\n         {\n            newAsh = this.ashs.shift();\n         }\n         this.ashs.push(newAsh);\n''','''         else\n         {\n            newAsh = this.ashs[this.ashCursor];\n            this.ashCursor = (this.ashCursor + 1) % this.ashs.length;\n         }\n         if(this.ashs.indexOf(newAsh) == -1)\n         {\n            this.ashs.push(newAsh);\n         }\n''','ash ring'),
('''         else\n         {\n            newBlood = this.bloods.shift();\n         }\n         this.bloods.push(newBlood);\n''','''         else\n         {\n            newBlood = this.bloods[this.bloodCursor];\n            this.bloodCursor = (this.bloodCursor + 1) % this.bloods.length;\n         }\n         if(this.bloods.indexOf(newBlood) == -1)\n         {\n            this.bloods.push(newBlood);\n         }\n''','blood ring'),
])

print('Stick War Complete V1 performance patch applied')
