#!/usr/bin/env python3
from pathlib import Path
import sys

if len(sys.argv)!=2: raise SystemExit('usage: patch_equipment_slots_v3.py <exported-scripts-root>')
root=Path(sys.argv[1]); base=root/'scripts'/'Game'

def patch_ui():
    p=base/'Interface'/'WorldMapFormationAcc.as'; t=p.read_text(encoding='utf-8-sig')
    def one(old,new,label):
        nonlocal t
        n=t.count(old)
        if n!=1: raise SystemExit(f'{label}: expected 1 match, got {n}')
        t=t.replace(old,new,1)
    one('''   import flash.display.MovieClip;\n   import flash.display.SimpleButton;\n''','''   import flash.display.MovieClip;\n   import flash.display.SimpleButton;\n   import flash.display.Sprite;\n''','acc Sprite import')
    one('''   import flash.text.TextField;\n''','''   import flash.text.TextField;\n   import flash.text.TextFormat;\n''','acc TextFormat import')
    one('''      private var selectSlotID:int = 0;\n''','''      private var selectSlotID:int = 0;\n      \n      private var equipSlotPage:int = 1;\n      private var equipSlotButton:Sprite = null;\n      private var equipSlotText:TextField = null;\n''','acc page vars')
    one('''         this.equip1.addEventListener(MouseEvent.CLICK,this.equip1Click,false,0,true);\n         this.slot1.addEventListener''','''         this.equip1.addEventListener(MouseEvent.CLICK,this.equip1Click,false,0,true);\n         this.expansionInstallEquipSlotButton();\n         this.slot1.addEventListener''','acc install page button')
    one('''         this.equip1.removeEventListener(MouseEvent.CLICK,this.equip1Click);\n         this.slot1.removeEventListener''','''         this.equip1.removeEventListener(MouseEvent.CLICK,this.equip1Click);\n         if(this.equipSlotButton != null)\n         {\n            this.equipSlotButton.removeEventListener(MouseEvent.CLICK,this.expansionEquipSlotClick);\n            if(this.equipSlotButton.parent != null) this.equipSlotButton.parent.removeChild(this.equipSlotButton);\n            this.equipSlotButton = null;\n            this.equipSlotText = null;\n         }\n         this.slot1.removeEventListener''','acc destroy page button')
    one('''         this.equip1.select.visible = false;\n         this.equip1.buttonMode = false;\n         var itemEquip:int = int(this.mGF.datMgr.unitGetValue(this.unitID,"item"));\n         if(itemEquip > 0)\n''','''         this.equip1.select.visible = false;\n         this.equip1.buttonMode = false;\n         var itemEquip:int = int(this.mGF.datMgr.unitGetValue(this.unitID,this.expansionEquipField()));\n         this.expansionUpdateEquipSlotLabel();\n         if(itemEquip > 0)\n''','acc updateView current equip field')
    helpers='''      private function expansionEquipField() : String\n      {\n         if(this.equipSlotPage == 2) return "item2";\n         if(this.equipSlotPage == 3) return "item3";\n         return "item";\n      }\n      \n      private function expansionInstallEquipSlotButton() : void\n      {\n         this.equipSlotButton = new Sprite();\n         this.equipSlotButton.graphics.beginFill(1973790,0.94);\n         this.equipSlotButton.graphics.lineStyle(1,6842472,1);\n         this.equipSlotButton.graphics.drawRoundRect(0,0,176,28,8,8);\n         this.equipSlotButton.graphics.endFill();\n         this.equipSlotButton.x = 292;\n         this.equipSlotButton.y = 65;\n         this.equipSlotButton.buttonMode = true;\n         this.equipSlotButton.addEventListener(MouseEvent.CLICK,this.expansionEquipSlotClick,false,0,true);\n         this.equipSlotText = new TextField();\n         this.equipSlotText.defaultTextFormat = new TextFormat("_sans",12,16777215,true,null,null,null,null,"center");\n         this.equipSlotText.width = 172;\n         this.equipSlotText.height = 24;\n         this.equipSlotText.x = 2;\n         this.equipSlotText.y = 4;\n         this.equipSlotText.mouseEnabled = false;\n         this.equipSlotText.selectable = false;\n         this.equipSlotButton.addChild(this.equipSlotText);\n         this.addChild(this.equipSlotButton);\n         this.expansionUpdateEquipSlotLabel();\n      }\n      \n      private function expansionEquipSlotClick(event:MouseEvent) : void\n      {\n         var unlocked:int = this.mGF.datMgr.expansionEquipmentSlotsUnlocked();\n         this.equipSlotPage++;\n         if(this.equipSlotPage > unlocked) this.equipSlotPage = 1;\n         this.selectEquipNum = 0;\n         this.selectEquipID = 0;\n         this.selectSlotNum = 0;\n         this.selectSlotID = 0;\n         this.updateView();\n      }\n      \n      private function expansionUpdateEquipSlotLabel() : void\n      {\n         if(this.equipSlotText == null) return;\n         var unlocked:int = this.mGF.datMgr.expansionEquipmentSlotsUnlocked();\n         if(this.equipSlotPage > unlocked) this.equipSlotPage = 1;\n         this.equipSlotText.text = "Equipment slot " + this.equipSlotPage + " / " + unlocked;\n      }\n      \n'''
    one('''      private function selectEQUIP(CLIP:*) : *\n''',helpers+'''      private function selectEQUIP(CLIP:*) : *\n''','acc page helpers')
    one('''      private function selectEQUIP(CLIP:*) : *\n      {\n         var itemEquip:int = int(this.mGF.datMgr.unitGetValue(this.unitID,"item"));\n         this.selectEquipID = 0;\n''','''      private function selectEQUIP(CLIP:*) : *\n      {\n         var itemEquip:int = int(this.mGF.datMgr.unitGetValue(this.unitID,this.expansionEquipField()));\n         this.selectEquipID = 0;\n''','acc select current field')
    one('''            itemEquip = int(this.mGF.datMgr.unitGetValue(this.unitID,"item"));\n            if(itemEquip > 0)\n            {\n               this.mGF.datMgr.unitSetValue(this.unitID,"item",0);\n''','''            itemEquip = int(this.mGF.datMgr.unitGetValue(this.unitID,this.expansionEquipField()));\n            if(itemEquip > 0)\n            {\n               this.mGF.datMgr.unitSetValue(this.unitID,this.expansionEquipField(),0);\n''','acc replace current item')
    one('''            this.mGF.datMgr.unitSetValue(this.unitID,"item",this.selectSlotID);\n''','''            this.mGF.datMgr.unitSetValue(this.unitID,this.expansionEquipField(),this.selectSlotID);\n''','acc equip selected item')
    one('''               this.mGF.datMgr.unitSetValue(this.unitID,"item",0);\n               itemTotal = int(this.mGF.datMgr.itemGetValue(this.selectEquipID));\n''','''               this.mGF.datMgr.unitSetValue(this.unitID,this.expansionEquipField(),0);\n               itemTotal = int(this.mGF.datMgr.itemGetValue(this.selectEquipID));\n''','acc remove current item')
    p.write_text(t,encoding='utf-8',newline='\n')
    for needle in ['equipSlotPage:int = 1','Equipment slot " + this.equipSlotPage','return "item2"','return "item3"','unitGetValue(this.unitID,this.expansionEquipField())']:
        if needle not in t: raise SystemExit('WorldMapFormationAcc missing '+needle)

def patch_stats():
    p=base/'System'/'StatDef'/'CharTotalStat.as'; t=p.read_text(encoding='utf-8-sig')
    def one(old,new,label):
        nonlocal t
        n=t.count(old)
        if n!=1: raise SystemExit(f'{label}: expected 1 match, got {n}')
        t=t.replace(old,new,1)
    one('''      public var unit_item_ability_id:int = 0;\n''','''      public var unit_item_ability_id:int = 0;\n      \n      public var unit_item2_ability_id:int = 0;\n      \n      public var unit_item3_ability_id:int = 0;\n''','item ability fields')
    one('''         var itemAbility:* = new CharAbilityStat(this.unit_item_ability_id);\n''','''         var itemAbility:* = new CharAbilityStat(this.unit_item_ability_id);\n         var itemAbility2:* = new CharAbilityStat(this.unit_item2_ability_id);\n         var itemAbility3:* = new CharAbilityStat(this.unit_item3_ability_id);\n''','item ability locals')

    numeric_lines = [
      ('this.pop = base.pop + ability1.pop + ability2.pop + ability3.pop + ability4.pop + ability5.pop + ability6.pop + ability7.pop + ability8.pop + ability9.pop + itemAbility.pop;',
       'this.pop = base.pop + ability1.pop + ability2.pop + ability3.pop + ability4.pop + ability5.pop + ability6.pop + ability7.pop + ability8.pop + ability9.pop + itemAbility.pop + itemAbility2.pop + itemAbility3.pop;'),
      ('this.health = base.health + ability1.health + ability2.health + ability3.health + ability4.health + ability5.health + ability6.health + ability7.health + ability8.health + ability9.health + itemAbility.health;',
       'this.health = base.health + ability1.health + ability2.health + ability3.health + ability4.health + ability5.health + ability6.health + ability7.health + ability8.health + ability9.health + itemAbility.health + itemAbility2.health + itemAbility3.health;'),
      ('mult = ability1.health_boost + ability2.health_boost + ability3.health_boost + ability4.health_boost + ability5.health_boost + ability6.health_boost + ability7.health_boost + ability8.health_boost + ability9.health_boost + itemAbility.health_boost;',
       'mult = ability1.health_boost + ability2.health_boost + ability3.health_boost + ability4.health_boost + ability5.health_boost + ability6.health_boost + ability7.health_boost + ability8.health_boost + ability9.health_boost + itemAbility.health_boost + itemAbility2.health_boost + itemAbility3.health_boost;'),
      ('this.health_regen = ability1.health_regen + ability2.health_regen + ability3.health_regen + ability4.health_regen + ability5.health_regen + ability6.health_regen + ability7.health_regen + ability8.health_regen + ability9.health_regen + itemAbility.health_regen;',
       'this.health_regen = ability1.health_regen + ability2.health_regen + ability3.health_regen + ability4.health_regen + ability5.health_regen + ability6.health_regen + ability7.health_regen + ability8.health_regen + ability9.health_regen + itemAbility.health_regen + itemAbility2.health_regen + itemAbility3.health_regen;'),
      ('this.attack = base.attack + ability1.attack + ability2.attack + ability3.attack + ability4.attack + ability5.attack + ability6.attack + ability7.attack + ability8.attack + ability9.attack + itemAbility.attack;',
       'this.attack = base.attack + ability1.attack + ability2.attack + ability3.attack + ability4.attack + ability5.attack + ability6.attack + ability7.attack + ability8.attack + ability9.attack + itemAbility.attack + itemAbility2.attack + itemAbility3.attack;'),
      ('mult = ability1.damage_mult + ability2.damage_mult + ability3.damage_mult + ability4.damage_mult + ability5.damage_mult + ability6.damage_mult + ability7.damage_mult + ability8.damage_mult + ability9.damage_mult + itemAbility.damage_mult;',
       'mult = ability1.damage_mult + ability2.damage_mult + ability3.damage_mult + ability4.damage_mult + ability5.damage_mult + ability6.damage_mult + ability7.damage_mult + ability8.damage_mult + ability9.damage_mult + itemAbility.damage_mult + itemAbility2.damage_mult + itemAbility3.damage_mult;'),
      ('this.attack_building = ability1.attack_building + ability2.attack_building + ability3.attack_building + ability4.attack_building + ability5.attack_building + ability6.attack_building + ability7.attack_building + ability8.attack_building + ability9.attack_building + itemAbility.attack_building;',
       'this.attack_building = ability1.attack_building + ability2.attack_building + ability3.attack_building + ability4.attack_building + ability5.attack_building + ability6.attack_building + ability7.attack_building + ability8.attack_building + ability9.attack_building + itemAbility.attack_building + itemAbility2.attack_building + itemAbility3.attack_building;'),
      ('this.reduce_damage = ability1.defense_mult + ability2.defense_mult + ability3.defense_mult + ability4.defense_mult + ability5.defense_mult + ability6.defense_mult + ability7.defense_mult + ability8.defense_mult + ability9.defense_mult + itemAbility.defense_mult;',
       'this.reduce_damage = ability1.defense_mult + ability2.defense_mult + ability3.defense_mult + ability4.defense_mult + ability5.defense_mult + ability6.defense_mult + ability7.defense_mult + ability8.defense_mult + ability9.defense_mult + itemAbility.defense_mult + itemAbility2.defense_mult + itemAbility3.defense_mult;'),
      ('this.speed = base.speed + ability1.speed + ability2.speed + ability3.speed + ability4.speed + ability5.speed + ability6.speed + ability7.speed + ability8.speed + ability9.speed + itemAbility.speed;',
       'this.speed = base.speed + ability1.speed + ability2.speed + ability3.speed + ability4.speed + ability5.speed + ability6.speed + ability7.speed + ability8.speed + ability9.speed + itemAbility.speed + itemAbility2.speed + itemAbility3.speed;')
    ]
    for old,new in numeric_lines:
        one('         '+old+'\n','         '+new+'\n','stack '+old.split(' = ')[0])

    one('''         if(itemAbility.attack_elemental != "")\n         {\n            this.attack_elemental = itemAbility.attack_elemental;\n         }\n''','''         if(itemAbility.attack_elemental != "") this.attack_elemental = itemAbility.attack_elemental;\n         if(itemAbility2.attack_elemental != "") this.attack_elemental = itemAbility2.attack_elemental;\n         if(itemAbility3.attack_elemental != "") this.attack_elemental = itemAbility3.attack_elemental;\n''','item elemental overrides')
    for prop in ['resist_strike','resist_slash','resist_pierce']:
        old=f'''         if(itemAbility.{prop} != 0 && itemAbility.{prop} > this.{prop})\n         {{\n            this.{prop} = itemAbility.{prop};\n         }}\n'''
        new=f'''         if(itemAbility.{prop} != 0 && itemAbility.{prop} > this.{prop}) this.{prop} = itemAbility.{prop};\n         if(itemAbility2.{prop} != 0 && itemAbility2.{prop} > this.{prop}) this.{prop} = itemAbility2.{prop};\n         if(itemAbility3.{prop} != 0 && itemAbility3.{prop} > this.{prop}) this.{prop} = itemAbility3.{prop};\n'''
        one(old,new,'item '+prop+' overrides')
    one('''         if(Boolean(itemAbility.resist_magic) && itemAbility.resist_magic > this.resist_magic)\n         {\n            this.resist_magic = itemAbility.resist_magic;\n         }\n''','''         if(Boolean(itemAbility.resist_magic) && itemAbility.resist_magic > this.resist_magic) this.resist_magic = itemAbility.resist_magic;\n         if(Boolean(itemAbility2.resist_magic) && itemAbility2.resist_magic > this.resist_magic) this.resist_magic = itemAbility2.resist_magic;\n         if(Boolean(itemAbility3.resist_magic) && itemAbility3.resist_magic > this.resist_magic) this.resist_magic = itemAbility3.resist_magic;\n''','item magic resist overrides')
    one('''         this.unit_item_ability_id = 0;\n         this.init(this.id);\n''','''         this.unit_item_ability_id = 0;\n         this.unit_item2_ability_id = 0;\n         this.unit_item3_ability_id = 0;\n         this.init(this.id);\n''','nonplayer item reset')
    one('''         var item:* = new CharItemStat(dat.unitGetValue(this.id,"item"));\n         this.unit_item_ability_id = item.ability_id;\n         this.init(this.id);\n''','''         var item:* = new CharItemStat(dat.unitGetValue(this.id,"item"));\n         var item2:* = new CharItemStat(dat.unitGetValue(this.id,"item2"));\n         var item3:* = new CharItemStat(dat.unitGetValue(this.id,"item3"));\n         this.unit_item_ability_id = item.ability_id;\n         this.unit_item2_ability_id = item2.ability_id;\n         this.unit_item3_ability_id = item3.ability_id;\n         this.init(this.id);\n''','player triple items')
    p.write_text(t,encoding='utf-8',newline='\n')
    for needle in ['unit_item2_ability_id','unit_item3_ability_id','itemAbility2.health','itemAbility3.attack','unitGetValue(this.id,"item2")','unitGetValue(this.id,"item3")']:
        if needle not in t: raise SystemExit('CharTotalStat missing '+needle)

patch_ui(); patch_stats(); print('Expansion V3 progressive three-slot equipment system applied')
